baseURL = "http://siteshshrivastava.com"
languageCode = "en-us"
title = "Sitesh Shrivastava"
theme = "introduction"
googleAnalytics = "UA-72677434-1"
publishDir = "docs"

[languages]
    [languages.en.params]
        description  = "Sitesh's home on the world wide web." # Max 160 characters show in search results
        footerText   = "2023 © Sitesh Shrivastava. All rights reserved." # Text to override default footer text (markdown allowed)

[params]
    themeStyle = "auto" # Choose "light" or "dark" or "auto"
    dateFormat = "Jan 1, 2023"
    email = "sitesh@siteshshrivastava.com"   # E-mail address for contact section

    [params.home]
        introHeight = "fullheight" # Input either "medium" or "large" or "fullheight"
        localTime = true # Show your current local time in contact section
        timeZone = "US/Pacific" # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat = "en-US" # Language specific format to use

    [[params.social]]
        url = "https://twitter.com/siteshps"
        icon = "twitter"
        icon_pack = "fab"
    [[params.social]]
        url = "https://linkedin.com/in/siteshshrivastava/"
        icon = "linkedin-in"
        icon_pack = "fab"
    [[params.social]]
        url = "https://github.com/sitz"
        icon = "github"
        icon_pack = "fab"
    [[params.social]]
        url = "https://medium.com/@siteshps"
        icon = "medium-m"
        icon_pack = "fab"
    [[params.social]]
        url = "https://instagram.com/siteshps"
        icon = "instagram"
        icon_pack = "fab"
    [[params.social]]
        url = "https://youtube.com/siteshshrivastava"
        icon = "youtube"
        icon_pack = "fab"
    [[params.social]]
        url = "https://goodreads.com/siteshps"
        icon = "goodreads-g"
        icon_pack = "fab"
    [[params.social]]
        url = "https://strava.com/athletes/siteshps"
        icon = "strava"
        icon_pack = "fab"
    [[params.social]]
        url = "https://last.fm/user/siteshps"
        icon = "lastfm"
        icon_pack = "fab"
    [[params.social]]
        url = "https://trakt.tv/users/siteshps"
        icon = "tv"
        icon_pack = "fas"
